# Generated by Django 3.0.8 on 2020-07-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200722_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='isbn',
        ),
        migrations.AddField(
            model_name='reader',
            name='idcard',
            field=models.CharField(default='', help_text='9/13 Character', max_length=13, verbose_name='ID card'),
        ),
    ]
