# Generated by Django 3.0.8 on 2020-07-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200722_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amount',
            field=models.IntegerField(default=1, help_text='Amount of book', max_length=100),
        ),
    ]
