# Generated by Django 3.0.8 on 2020-07-23 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_book_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='borrowed',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='catalog.BookInstance'),
        ),
        migrations.AlterField(
            model_name='book',
            name='amount',
            field=models.IntegerField(default=1, help_text='Amount of book'),
        ),
    ]
