# Generated by Django 3.0.8 on 2020-07-23 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200723_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='borrowed',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='catalog.Book'),
        ),
    ]
