# Generated by Django 3.0.8 on 2020-07-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20200723_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reader',
            old_name='book',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='reader',
            name='idcard',
            field=models.CharField(default='', help_text='9/13 Character', max_length=13, verbose_name='ID card'),
        ),
    ]
