# Generated by Django 3.0.8 on 2020-07-23 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20200723_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='amount',
        ),
    ]
