# Generated by Django 3.0.8 on 2020-07-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_remove_reader_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='borrow_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
