# Generated by Django 3.0.8 on 2020-07-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20200723_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='borrow_at',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(blank=True, null=True),
        ),
    ]
