# Generated by Django 3.0.8 on 2020-07-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20200723_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='borrow_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
