# Generated by Django 3.0.8 on 2020-07-23 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_bookinstance_borrow_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='borrow_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
