# Generated by Django 3.0.8 on 2020-07-23 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_remove_bookinstance_borrow_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='borrow_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reader',
            name='idcard',
            field=models.CharField(default='', help_text='9/12 Character', max_length=12, verbose_name='ID card'),
        ),
    ]
